#pragma once
#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/vec4.hpp>
#include <glm/mat4x4.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include "Core/Window.h"
#include "Core/Application.h"
#include "Core/log.h"
#include "Core/Timer.h"
#include "Renderer/RenderDevice.h"
#include "Renderer/Font.h"
#include "Renderer/Sprite.h"
#include "Renderer/Texture.h"
#include "Renderer/ParticleSwarm.h"
#include "Renderer/Line.h"
#include "Renderer/ShaderManager.h"
#include "Renderer/Light.h"
#include "Renderer/Shader.h"
#include "Renderer/Model.h"
#include "Renderer/Mesh.h"
#include "Renderer/Material.h"